name: Hello world

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      MESSAGE: Fin des étapes.
    steps:
      - name: Hello
        run: echo "Hello World"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Initialize
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Secretto
        run:  echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Afficher Secret
        run: echo $API_KEY

      - name: Générer rapport
        run: echo "Rapport de tests" > rapport.txt

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-artifact
          path: rapport.txt

      - name: Fin
        run: echo $MESSAGE